apiVersion: mindxdl.gitee.com/v1
kind: AscendJob
metadata:
  name: default-infer-test-pytorch-910b
  labels:
    framework: pytorch
    ring-controller.atlas: ascend-910b
    fault-scheduling: "force"
    huawei.com/scheduler.softShareDev.aicoreQuota: "50" # soft share device core quota, unit: %
    huawei.com/scheduler.softShareDev.hbmQuota: "2048" # soft share device hbm quota, unit: MB
    huawei.com/scheduler.softShareDev.policy: "fixed-share" # 1:fixed-share 2:elastic 3:best-effort
  annotations:
    huawei.com/schedule_policy: "chip1-softShareDev" # soft share device volcano schedule policy
spec:
  schedulerName: volcano   # work when enableGangScheduling is true
  runPolicy:
    schedulingPolicy:      # work when enableGangScheduling is true
      minAvailable: 2 # soft share dev tasks with multiple replicas are only supported for single-machine scenarios.
      queue: default
  successPolicy: AllWorkers
  replicaSpecs:
    Master:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: job-name
                        operator: In
                        values:
                          - default-infer-test-pytorch-910b
                  topologyKey: kubernetes.io/hostname
          automountServiceAccountToken: false
          nodeSelector:
            host-arch: huawei-arm
            accelerator-type: module-910b-8 # depend on your device model, 910bx8 is module-910b-8 ,910bx16 is module-910b-16
          containers:
            - name: ascend # do not modify
              image: pytorch-test:latest         # trainning framework image， which can be modified
              imagePullPolicy: IfNotPresent
              env:
                - name: XDL_IP                                       # IP address of the physical node, which is used to identify the node where the pod is running
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              command:                           # training command, which can be modified
                - /bin/bash
                - -c
              args: [ "./infer.sh" ]
              ports:                          # default value containerPort: 2222 name: ascendjob-port if not set
                - containerPort: 2222         # determined by user
                  name: ascendjob-port        # do not modify
              resources:
                requests:
                  huawei.com/Ascend910: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
                limits:
                  huawei.com/Ascend910: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
              volumeMounts:
                - name: ascend-driver
                  mountPath: /usr/local/Ascend/driver
                - name: ascend-add-ons
                  mountPath: /usr/local/Ascend/add-ons
                - name: dshm
                  mountPath: /dev/shm
                - name: localtime
                  mountPath: /etc/localtime
                - name: share-device-config-dir # soft split configuration folder path
                  mountPath: /etc/enpu/vcann-rt/
                - name: libpreload # soft split dynamic library path
                  mountPath: /opt/enpu/vcann-rt/lib/libvruntime.so
                - name: preload # preload configuration file path
                  mountPath: ${preload_path}/ld.so.preload
          volumes:
            - name: ascend-driver
              hostPath:
                path: /usr/local/Ascend/driver
            - name: ascend-add-ons
              hostPath:
                path: /usr/local/Ascend/add-ons
            - name: dshm
              emptyDir:
                medium: Memory
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: share-device-config-dir # soft split configuration folder path
              hostPath:
                path: /etc/enpu/vcann-rt/vnpu.vnpu-base/ # {configuration folder path}/${namespace}.${container_name}/
                type: DirectoryOrCreate
            - name: libpreload # soft split dynamic library path
              hostPath:
                path: /opt/enpu/vcann-rt/lib/libvruntime.so
            - name: preload # preload configuration file path
              hostPath:
                path: ${preload_path}/ld.so.preload
    Worker:
      replicas: 1
      restartPolicy: Never
      template:
        metadata:
          labels:
            ring-controller.atlas: ascend-910b
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: job-name
                        operator: In
                        values:
                          - default-infer-test-pytorch-910b
                  topologyKey: kubernetes.io/hostname
          automountServiceAccountToken: false
          nodeSelector:
            host-arch: huawei-arm
            accelerator-type: module-910b-8 # depend on your device model, 910bx8 is module-910b-8 ,910bx16 is module-910b-16
          containers:
            - name: ascend # do not modify
              image: pytorch-test:latest         # trainning framework image， which can be modified
              imagePullPolicy: IfNotPresent
              env:
                - name: XDL_IP                                       # IP address of the physical node, which is used to identify the node where the pod is running
                  valueFrom:
                    fieldRef:
                      fieldPath: status.hostIP
              command: # training command, which can be modified
                - /bin/bash
                - -c
              args: [ "./infer.sh" ]
              ports: # default value containerPort: 2222 name: ascendjob-port if not set
                - containerPort: 2222         # determined by user
                  name: ascendjob-port        # do not modify
              resources:
                requests:
                  huawei.com/Ascend910: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
                limits:
                  huawei.com/Ascend910: 50 # should be equal to huawei.com/scheduler.softShareDev.aicoreQuota
              volumeMounts:
                - name: ascend-driver
                  mountPath: /usr/local/Ascend/driver
                - name: ascend-add-ons
                  mountPath: /usr/local/Ascend/add-ons
                - name: dshm
                  mountPath: /dev/shm
                - name: localtime
                  mountPath: /etc/localtime
                - name: share-device-config-dir # soft split configuration folder path
                  mountPath: /etc/enpu/vcann-rt/
                - name: libpreload # soft split dynamic library path
                  mountPath: /opt/enpu/vcann-rt/lib/libvruntime.so
                - name: preload # preload configuration file path
                  mountPath: ${preload_path}/ld.so.preload
          volumes:
            - name: ascend-driver
              hostPath:
                path: /usr/local/Ascend/driver
            - name: ascend-add-ons
              hostPath:
                path: /usr/local/Ascend/add-ons
            - name: dshm
              emptyDir:
                medium: Memory
            - name: localtime
              hostPath:
                path: /etc/localtime
            - name: share-device-config-dir # soft split configuration folder path
              hostPath:
                path: /etc/enpu/vcann-rt/vnpu.vnpu-base/ # {configuration folder path}/${namespace}.${container_name}/
                type: DirectoryOrCreate
            - name: libpreload # soft split dynamic library path
              hostPath:
                path: /opt/enpu/vcann-rt/lib/libvruntime.so
            - name: preload # preload configuration file path
              hostPath:
                path: ${preload_path}/ld.so.preload

